### registration user / create new user
POST http://localhost:3000/api/v1/users/registration
Content-Type: application/json

{
    "name": "martDASin",
    "surname": "Macford",
    "nickname": "",
    "age": 20,
    "password": "Admin",
    "email": "marADAStin@gmail.com",
    "role": "user"
}
### Authorization User
POST http://localhost:3000/api/v1/users/authorization
Content-Type: application/json 

{
    "nickname": "Admin",
    "password": "Admin"
}
### search book 
GET http://localhost:3000/api/v1/books/search?query=it
Authentication: token 
### read book
GET http://localhost:3000/api/v1/books/read/5b820412f920ef1f5099459d
Authentication: token 
### add comment 
POST http://localhost:3000/api/v1/books/comment/5b84aa038d8a79057808c869
Content-Type: application/json
Authentication: token 

{
    "comment": "nice adasda",
    "nickname": "Jhon"
}

//Admin command

### add book to db 
POST http://localhost:3000/api/v1/books/add
Content-Type: application/json
Authentication: token 

{
	"name": "It",
	"author": "King",
	"description": "Horror",
	"text": "Lorem ipsum tecto ex dolores?"
}

### change a book
POST http://localhost:3000/api/v1/books/change/5b81e86c47277b200c67c3ac
Content-Type: application/json
Authentication: token 

{
	"author": "Lara"
}
### get comments for user name
GET http://localhost:3000/api/v1/comments/searchuser?name=martin
Authentication: token 

### delate all comment by username
DELETE http://localhost:3000/api/v1/comments/searchuser?name=martin
Authentication: token 

### delete comment by comment id
DELETE http://localhost:3000/api/v1/comments/searchid?id=5b9577418efdc41b20005adb
Authentication: token 
